### ISSUE TITLE
Question: Is it possible to trigger the click on hover for the treeview

### ISSUE THREAD

**Issue by cimachris** [leolorenzoluis/xyz.drop-down-tree-view#83]
Sorry if the question is a little begininer.  But I'm looking to have the tree view appear on hover of the input.  Also, thank you for this awesome module.  I'm loving it!

**Comment by leolorenzoluis** [comment]
Hello,

Thanks for using the component! Yes it is absolutely possible, but why would you want to trigger click on hover? Wouldn't that be a bad user experience especially on mobile?
