### ISSUE TITLE
Production Builds Failing with module

### ISSUE THREAD

**Issue by cimachris** [leolorenzoluis/xyz.drop-down-tree-view#84]
I had to remove this for now.  But I'm not able to compile with the most current version.  My package file for all of the items that I have installed are:
`{
  "name": "cimaang",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/cli": "^1.0.6",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
    "@progress/kendo-angular-buttons": "^1.0.0",
    "@progress/kendo-angular-dateinputs": "^1.0.1",
    "@progress/kendo-angular-dropdowns": "^1.0.9",
    "@progress/kendo-angular-excel-export": "^1.0.0",
    "@progress/kendo-angular-grid": "^1.1.2",
    "@progress/kendo-angular-inputs": "^1.0.3",
    "@progress/kendo-angular-intl": "^1.0.0",
    "@progress/kendo-angular-l10n": "^1.0.0",
    "@progress/kendo-angular-layout": "^1.0.2",
    "@progress/kendo-angular-upload": "^1.0.0",
    "@progress/kendo-data-query": "^1.0.1",
    "@progress/kendo-date-math": "^1.0.1",
    "@progress/kendo-drawing": "^1.0.3",
    "@progress/kendo-file-saver": "^1.0.1",
    "@progress/kendo-theme-bootstrap": "^2.4.0",
    "@progress/kendo-theme-default": "^2.37.0",
    "angular-date-value-accessor": "0.0.2",
    "angular-ide": "^0.9.23",
    "angular-tree-component": "^3.7.2",
    "angular2-image-gallery": "^1.0.1",
    "angular2-notifications": "^0.7.4",
    "angular2-uuid": "^1.1.1",
    "core-js": "^2.4.1",
    "gm": "^1.23.0",
    "hammerjs": "^2.0.8",
    "ng": "0.0.0-rc6",
    "ng-photoswipe": "^0.2.0",
    "ng2-file-upload": "^1.2.1",
    "rxjs": "^5.4.0",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.47",
    "@types/node": "~7.0.22",
    "angular-ide": "^0.9.21",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
`

**Comment by leolorenzoluis** [comment]
Hello,

What is the error that you are getting?
